### PR TITLE
Add tests to ensure that the wrapper functions pass back return values

### PR DESCRIPTION
**Pull request by ide**
Added two simple tests that ensure that the return value of the body functions are returned by the wrapper functions.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
This appears to no longer merge cleanly now that #4 was merged, mind updating it?

**Comment by ide** [comment]
Yep, updating!

**Comment by kevinsawicki** [comment]
Thanks for updating

**Comment by kevinsawicki** [comment]
Published in 1.1.0

**Pull request merged**
